components:
  schemas:
    Summary:
      type: object
      properties:
        segment_id:
          type: integer
          description: Identifiant du segment dans la couche TLM3D
        closed:
          type: boolean
          description: Status du segment (true = fermé; false = ouvert)
        avg_load:
          type: float
          description: Charge moyenne de trafic sur le segment ^
        load_impact:
          type: float
          description: Impact de la fermeture des segments par rapport au scénario de base (Variation en %).