type: object
properties:
  segment_id:
    type: integer
    description: Identifiant unique du segment dans la couche TLM3D
  closed:
    type: boolean
    description: Statut du segment (true = fermé; false = ouvert)
  avg_load:
    type: number
    format: float
    description: Charge moyenne de trafic sur le segment
  load_impact:
    type: number
    format: float
    description: Impact de la fermeture des segments par rapport au scénario de base (variation en %)